/-
  Sigma Algebra: Intersection vs Union
  =====================================

  We prove two things:

  1. (General) The intersection of two σ-algebras is always a σ-algebra.
     This follows from the fact that `MeasurableSpace α` forms a lattice in Mathlib,
     so `m₁ ⊓ m₂` is a well-formed `MeasurableSpace`.

  2. (Counterexample) The union of two σ-algebras need NOT be a σ-algebra.
     We exhibit two concrete σ-algebras on Ω = Fin 3 = {0, 1, 2}:

       F₁ = {∅, {0}, {1,2}, Ω}
       F₂ = {∅, {1}, {0,2}, Ω}

     Their union F₁ ∪ F₂ contains {0} and {1}, but does NOT contain {0,1},
     so it fails to be closed under finite union, hence is not a σ-algebra.

  Lean version: Lean 4 with Mathlib
-/

import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Fin.Basic

open Finset

-- ============================================================================
-- PART 1: Intersection of σ-algebras is a σ-algebra (general result)
-- ============================================================================

/-
  In Mathlib, `MeasurableSpace α` has a `Lattice` (in fact `CompleteLattice`)
  instance. The infimum `m₁ ⊓ m₂` is a `MeasurableSpace` whose measurable sets
  are exactly those measurable in both `m₁` and `m₂`.

  So the intersection result is essentially definitional.
-/

/-- The infimum of two σ-algebras is a σ-algebra whose measurable sets are
    the intersection of the two families of measurable sets. -/
theorem sigmaAlgebra_inter_is_sigmaAlgebra
    {α : Type*} (m₁ m₂ : MeasurableSpace α) :
    ∃ m : MeasurableSpace α,
      ∀ s : Set α, @MeasurableSet α m s ↔
        (@MeasurableSet α m₁ s ∧ @MeasurableSet α m₂ s) := by
  exact ⟨m₁ ⊓ m₂, fun s => Iff.rfl⟩

/-- Alternatively, we can just define it directly — Lean accepts this because
    `⊓` on `MeasurableSpace` is well-typed. -/
def intersectionSigmaAlgebra {α : Type*}
    (m₁ m₂ : MeasurableSpace α) : MeasurableSpace α :=
  m₁ ⊓ m₂


-- ============================================================================
-- PART 2: Union of σ-algebras need NOT be a σ-algebra (counterexample)
-- ============================================================================

/-
  We work concretely with `Fin 3` and use `Finset` so that everything is
  decidable, allowing the `decide` tactic to close goals automatically.

  Ω = Fin 3 = {0, 1, 2}

  F₁ = {∅, {0}, {1,2}, {0,1,2}}        — σ-algebra generated by {0}
  F₂ = {∅, {1}, {0,2}, {0,1,2}}        — σ-algebra generated by {1}
-/

/-- The first σ-algebra: {∅, {0}, {1,2}, {0,1,2}} -/
def F₁ : Finset (Finset (Fin 3)) :=
  {∅, {0}, {1, 2}, Finset.univ}

/-- The second σ-algebra: {∅, {1}, {0,2}, {0,1,2}} -/
def F₂ : Finset (Finset (Fin 3)) :=
  {∅, {1}, {0, 2}, Finset.univ}

/-- The "union" of the two collections of sets. -/
def F_union : Finset (Finset (Fin 3)) :=
  F₁ ∪ F₂

-- ---------------------------------------------------------------------------
-- Step 2a: Verify that F₁ and F₂ are σ-algebras (on a finite type,
--          this means: contain ∅, closed under complement and union).
-- ---------------------------------------------------------------------------

/-- F₁ contains the empty set -/
theorem F₁_empty : (∅ : Finset (Fin 3)) ∈ F₁ := by decide

/-- F₁ contains Ω -/
theorem F₁_univ : Finset.univ ∈ F₁ := by decide

/-- F₁ is closed under complement (relative to Fin 3).
    For each A ∈ F₁, we have Finset.univ \ A ∈ F₁. -/
theorem F₁_compl_closed :
    ∀ A ∈ F₁, Finset.univ \ A ∈ F₁ := by decide

/-- F₁ is closed under pairwise union. -/
theorem F₁_union_closed :
    ∀ A ∈ F₁, ∀ B ∈ F₁, A ∪ B ∈ F₁ := by decide

/-- F₂ contains the empty set -/
theorem F₂_empty : (∅ : Finset (Fin 3)) ∈ F₂ := by decide

/-- F₂ contains Ω -/
theorem F₂_univ : Finset.univ ∈ F₂ := by decide

/-- F₂ is closed under complement. -/
theorem F₂_compl_closed :
    ∀ A ∈ F₂, Finset.univ \ A ∈ F₂ := by decide

/-- F₂ is closed under pairwise union. -/
theorem F₂_union_closed :
    ∀ A ∈ F₂, ∀ B ∈ F₂, A ∪ B ∈ F₂ := by decide

-- ---------------------------------------------------------------------------
-- Step 2b: The union F₁ ∪ F₂ is NOT a σ-algebra.
-- ---------------------------------------------------------------------------

/-- {0} is in the union (it comes from F₁). -/
theorem singleton_zero_in_union : ({0} : Finset (Fin 3)) ∈ F_union := by
  simp [F_union]
  decide

/-- {1} is in the union (it comes from F₂). -/
theorem singleton_one_in_union : ({1} : Finset (Fin 3)) ∈ F_union := by
  simp [F_union]
  decide

/-- {0, 1} is NOT in the union. -/
theorem pair_01_not_in_union : ({0, 1} : Finset (Fin 3)) ∉ F_union := by
  decide

/-- Therefore the union is not closed under set union:
    {0} ∈ F_union, {1} ∈ F_union, but {0} ∪ {1} = {0,1} ∉ F_union.
    This means F_union cannot be a σ-algebra. -/
theorem union_not_closed_under_union :
    ∃ A ∈ F_union, ∃ B ∈ F_union, A ∪ B ∉ F_union := by
  exact ⟨{0}, singleton_zero_in_union, {1}, singleton_one_in_union, pair_01_not_in_union⟩

/-- Packaging the full result: σ-algebra union need not be a σ-algebra. -/
theorem sigmaAlgebra_union_not_sigmaAlgebra :
    ¬ (∀ A ∈ F_union, ∀ B ∈ F_union, A ∪ B ∈ F_union) := by
  intro h
  have := h {0} singleton_zero_in_union {1} singleton_one_in_union
  exact pair_01_not_in_union this


-- ============================================================================
-- PART 3 (Bonus): The intersection F₁ ∩ F₂ IS a σ-algebra, concretely.
-- ============================================================================

/-- The concrete intersection: F₁ ∩ F₂ = {∅, {0,1,2}} -/
def F_inter : Finset (Finset (Fin 3)) :=
  F₁ ∩ F₂

/-- The intersection equals {∅, Ω}. -/
theorem F_inter_eq : F_inter = {∅, Finset.univ} := by decide

/-- The intersection contains ∅. -/
theorem F_inter_empty : (∅ : Finset (Fin 3)) ∈ F_inter := by decide

/-- The intersection contains Ω. -/
theorem F_inter_univ : Finset.univ ∈ F_inter := by decide

/-- The intersection is closed under complement. -/
theorem F_inter_compl_closed :
    ∀ A ∈ F_inter, Finset.univ \ A ∈ F_inter := by decide

/-- The intersection is closed under union. -/
theorem F_inter_union_closed :
    ∀ A ∈ F_inter, ∀ B ∈ F_inter, A ∪ B ∈ F_inter := by decide
